"""add confirmation

Revision ID: 36c6a5eec9cb
Revises: 448791d81d96
Create Date: 2014-11-09 16:43:31.881363

"""

# revision identifiers, used by Alembic.
revision = '36c6a5eec9cb'
down_revision = '448791d81d96'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
