"""fixed roles?

Revision ID: 4b8e84657406
Revises: 535a47795070
Create Date: 2014-11-13 22:15:53.597346

"""

# revision identifiers, used by Alembic.
revision = '4b8e84657406'
down_revision = '535a47795070'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
