"""add roles

Revision ID: 535a47795070
Revises: 395c9ff9e36a
Create Date: 2014-11-13 22:01:28.279525

"""

# revision identifiers, used by Alembic.
revision = '535a47795070'
down_revision = '395c9ff9e36a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
